services:
  app:
    build: .
    image: tokenization-api:latest
    container_name: tokenization-api
    environment:
      SPRING_DATASOURCE_URL: "jdbc:oracle:thin:@//oracle-xe:1521/XEPDB1"
      SPRING_DATASOURCE_USERNAME: "${DB_USERNAME:-amit}"
      SPRING_DATASOURCE_PASSWORD: "${DB_PASSWORD}"
      SERVER_PORT: "8088"
      TOKENIZATION_HMAC_KEY_BASE64: "${HMAC_KEY_BASE64}"
      AWS_REGION: "${AWS_REGION:-ap-south-1}"
      AWS_KMS_KEY_ID: "${AWS_KMS_KEY_ID}"
    ports:
      - "8088:8088"
    networks:
      - kafka-net
    volumes:
      - "~/.aws:/root/.aws:ro"

networks:
  kafka-net:
    external: true
