openapi: 3.0.3
info:
  title: Tokenization API
  version: 1.0.0
  description: Deterministic credit-card tokenization and detokenization.
servers:
  - url: http://localhost:8088
paths:
  /api/tokenize:
    post:
      summary: Tokenize a credit card number
      parameters:
        - in: header
          name: source
          required: true
          schema:
            type: string
          description: Identifies the calling system or application
        - in: header
          name: correlationId
          required: true
          schema:
            type: string
          description: Unique identifier for request tracing and correlation
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TokenizeRequest'
      responses:
        '201':
          description: Created
          headers:
            Location:
              description: Detokenize link
              schema:
                type: string
            source:
              description: Echoed from request
              schema:
                type: string
            correlationId:
              description: Echoed from request
              schema:
                type: string
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TokenizeResponse'
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ValidationError'
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /api/detokenize:
    get:
      summary: Detokenize a token back to credit card number
      parameters:
        - in: header
          name: source
          required: true
          schema:
            type: string
          description: Identifies the calling system or application
        - in: header
          name: correlationId
          required: true
          schema:
            type: string
          description: Unique identifier for request tracing and correlation
        - in: query
          name: token
          required: true
          schema:
            type: string
            pattern: '^9\\d{15}$'
          description: 16-digit token starting with 9
      responses:
        '200':
          description: OK
          headers:
            source:
              description: Echoed from request
              schema:
                type: string
            correlationId:
              description: Echoed from request
              schema:
                type: string
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DetokenizeResponse'
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
components:
  schemas:
    TokenizeRequest:
      type: object
      required: [ccNumber]
      properties:
        ccNumber:
          type: string
          pattern: '^\\d{16}$'
          description: 16-digit credit card number
    TokenizeResponse:
      type: object
      properties:
        token:
          type: string
          pattern: '^9\\d{15}$'
          description: 16-digit token starting with 9
    DetokenizeResponse:
      type: object
      properties:
        ccNumber:
          type: string
          pattern: '^\\d{16}$'
    Error:
      type: object
      properties:
        error:
          type: string
    ValidationError:
      type: object
      description: Field-specific validation error messages
      additionalProperties:
        type: string
      example:
        ccNumber: "ccNumber must be exactly 16 digits"
        source: "source header must not be blank"
        correlationId: "correlationId header must not be blank"
